URL_PREFIX = 'https://'
BASE_URL = 'tryfynd.com'

FEATURE_FLAG_SERVICE_SUBDOMAIN = 'api.'
FEATURE_FLAG_STATUS_CHECK_URL = URL_PREFIX + FEATURE_FLAG_SERVICE_SUBDOMAIN + BASE_URL + '/v1/featureflag/status/'
